server:
  port: 8081
t1:
  scan-path: Energeenot.secondAppForT1_java
  kafka:
    bootstrap:
      server: ${KAFKA_SERVER:localhost:9092}

transaction:
  max-count: 3
  time-window-ms: 60000

spring:
  application:
    name: secondAppForT1_java
  datasource:
    url: jdbc:postgresql://localhost:5432/t1_java_second_service
    username: "postgres"
    password: "postgresql"
    driverClassName: org.postgresql.Driver
